name: Feature Request 1
description: Request a new feature 🪄
labels: ['story']
body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to submit a feature request! Please fill out this form as completely as possible.
  - type: dropdown
    id: project
    attributes:
      multiple: true
      label: Which area is this feature request for?
      options:
        - Website User Interface
        - Command Line Tools
        - LaTeX Export
        - Microsoft Word Export
        - Javascript Packages (please list)
        - Other
    validations:
      required: true

  - type: textarea
    id: describe
    attributes:
      label: Feature Request
      value: |
        ##  Describe the feature you'd like to request
        <!--  A clear and concise description of what you want and what your use case is. -->
        
        ##  Describe the solution you'd like
        <!-- A clear and concise description of what you want to happen. -->
        
        ##  Describe alternatives you've considered
        <!-- A clear and concise description of any alternative solutions or features you've considered. -->
